#!/usr/bin/env python3
"""
XGBoost Solar Power Prediction (multi-step, 16-point)
======================================================
Task  : Given 96-step (24h) history, predict next 16 steps (4h ahead).
Data  : Uses the SAME fixed .npy splits as the ED / RoPE models
        (generated by solar_preprocess.py: 70% train / 15% val / 15% test)
Eval  : ACC1, ACC2 (国标), RMSE, MAE — identical to ED evaluation,
        plus per-step breakdown for all 16 prediction points.

Usage:
  python xgboost_solar_power.py            # preprocess + train + evaluate
  python xgboost_solar_power.py --skip-preprocess   # skip if .npy already exist
"""

import numpy as np
import pickle
import argparse
import os

from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ─────────────────────────────────────────────────────────────
# 1.  Feature extraction from encoder/decoder arrays
# ─────────────────────────────────────────────────────────────
# X_enc : [N, 96, 13]   96-step history (time×6 + weather×6 + power×1)
# X_dec : [N, 16, 12]   future 16-step weather+time forecast (no power)
# y     : [N, 16]       target (normalised power)

def make_features(X_enc: np.ndarray, X_dec: np.ndarray) -> np.ndarray:
    """
    Flatten enc/dec arrays into a 2-D feature matrix for XGBoost.

    From encoder (96 steps × 13 features):
      • raw last 32 steps  (recent 8h)     → 32 × 13 = 416 cols
      • global mean + std over 96 steps    →  2 × 13 =  26 cols
      • last-step values                   →       13 =  13 cols

    From decoder (16 steps × 12 features):
      • all future weather+time features   → 16 × 12 = 192 cols

    Total: 416 + 26 + 13 + 192 = 647 features
    """
    N = X_enc.shape[0]

    # --- encoder features ---
    last32  = X_enc[:, -32:, :].reshape(N, -1)          # [N, 416]
    enc_mean = X_enc.mean(axis=1)                         # [N, 13]
    enc_std  = X_enc.std(axis=1)                          # [N, 13]
    last1   = X_enc[:, -1, :]                             # [N,  13]

    # --- decoder features (future weather) ---
    dec_flat = X_dec.reshape(N, -1)                       # [N, 192]

    feat = np.concatenate([last32, enc_mean, enc_std, last1, dec_flat], axis=1)
    return feat.astype(np.float32)


# ─────────────────────────────────────────────────────────────
# 2.  Evaluation metrics (identical to solar_train_ed.py)
# ─────────────────────────────────────────────────────────────

def calc_acc1(y_true: np.ndarray, y_pred: np.ndarray, cap: float = 1.0) -> float:
    """ACC1 (MAE-based): 1 - MAE / mean(y_true),  only on non-zero timesteps."""
    mask = y_true > 0.01
    if mask.sum() == 0:
        return float("nan")
    y_t = y_true[mask] * cap
    y_p = y_pred[mask] * cap
    mae = np.mean(np.abs(y_t - y_p))
    avg = np.mean(y_t)
    return max(0.0, 1.0 - mae / (avg + 1e-6))


def calc_acc2(y_true: np.ndarray, y_pred: np.ndarray, cap: float = 1.0) -> float:
    """ACC2 (国标): 1 - sqrt( mean( ((P_M - P_P) / max(P_M, 0.2*Cap))^2 ) )"""
    p_m = y_true.flatten() * cap
    p_p = y_pred.flatten() * cap
    denom = np.maximum(p_m, 0.2 * cap)
    return max(0.0, 1.0 - np.sqrt(np.mean(((p_m - p_p) / denom) ** 2)))


def calc_rmse(y_true: np.ndarray, y_pred: np.ndarray, cap: float = 1.0) -> float:
    return float(np.sqrt(np.mean((y_true * cap - y_pred * cap) ** 2)))


def calc_mae(y_true: np.ndarray, y_pred: np.ndarray, cap: float = 1.0) -> float:
    return float(np.mean(np.abs(y_true * cap - y_pred * cap)))


def print_metrics(y_true, y_pred, cap, label=''):
    acc1 = calc_acc1(y_true, y_pred, cap)
    acc2 = calc_acc2(y_true, y_pred, cap)
    rmse = calc_rmse(y_true, y_pred, cap)
    mae  = calc_mae(y_true, y_pred, cap)
    print(f"\n{'='*60}")
    print(f"  {label}")
    print(f"{'='*60}")
    print(f"  ACC1 (MAE-based): {acc1:.4f}  ({acc1*100:.2f}%)")
    print(f"  ACC2 (国标):      {acc2:.4f}  ({acc2*100:.2f}%)")
    print(f"  RMSE:             {rmse:.4f} MW")
    print(f"  MAE:              {mae:.4f} MW")
    print(f"{'='*60}")
    return acc1, acc2, rmse, mae


def print_per_step(y_true, y_pred, cap, num_steps=16):
    """Identical format to solar_train_rope_v3.py evaluate()."""
    print(f"\n按预测步 (每步15分钟, 共{num_steps}步):")
    print(f"  {'步':>3s}  {'时刻':>7s}  {'ACC1':>7s}  {'ACC2':>7s}  "
          f"{'RMSE(MW)':>9s}  {'MAE(MW)':>8s}")
    print(f"  {'-'*3}  {'-'*7}  {'-'*7}  {'-'*7}  {'-'*9}  {'-'*8}")

    step_metrics = []
    for step in range(num_steps):
        yt = y_true[:, step:step+1]
        yp = y_pred[:, step:step+1]
        s_acc1 = calc_acc1(yt, yp, cap)
        s_acc2 = calc_acc2(yt, yp, cap)
        s_rmse = calc_rmse(yt, yp, cap)
        s_mae  = calc_mae(yt, yp, cap)
        minutes = (step + 1) * 15
        time_label = f"+{minutes}min"
        print(f"  {step+1:3d}  {time_label:>7s}  {s_acc1:.4f}  {s_acc2:.4f}  "
              f"{s_rmse:9.4f}  {s_mae:8.4f}")
        step_metrics.append((s_acc1, s_acc2, s_rmse, s_mae))
    return step_metrics


# ─────────────────────────────────────────────────────────────
# 3.  Train
# ─────────────────────────────────────────────────────────────

def train(data_dir='.'):
    print("\n[2/3] 模型训练")

    X_enc_train = np.load(os.path.join(data_dir, "X_enc_train.npy"))
    X_dec_train = np.load(os.path.join(data_dir, "X_dec_train.npy"))
    y_train     = np.load(os.path.join(data_dir, "y_train.npy"))
    X_enc_val   = np.load(os.path.join(data_dir, "X_enc_val.npy"))
    X_dec_val   = np.load(os.path.join(data_dir, "X_dec_val.npy"))
    y_val       = np.load(os.path.join(data_dir, "y_val.npy"))

    with open(os.path.join(data_dir, "norm_params.pkl"), "rb") as f:
        norm_params = pickle.load(f)
    cap = norm_params["power"]["cap"]

    print(f"训练集: enc={X_enc_train.shape}, dec={X_dec_train.shape}, y={y_train.shape}")
    print(f"验证集: enc={X_enc_val.shape},   dec={X_dec_val.shape},   y={y_val.shape}")
    print(f"标称容量: {cap} MW")

    X_tr = make_features(X_enc_train, X_dec_train)
    X_vl = make_features(X_enc_val,   X_dec_val)
    print(f"特征维度: {X_tr.shape[1]}")

    base = XGBRegressor(
        n_estimators=800,
        learning_rate=0.05,
        max_depth=6,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.7,
        reg_alpha=0.1,
        reg_lambda=1.0,
        objective='reg:squarederror',
        tree_method='hist',
        random_state=42,
        n_jobs=-1,
        eval_metric='rmse',
        early_stopping_rounds=30,
    )

    # MultiOutputRegressor trains one XGBRegressor per output step
    model = MultiOutputRegressor(base, n_jobs=1)

    print("\n训练 MultiOutputRegressor (16 个 XGBoost 模型, 每步一个) ...")
    # Pass eval sets for early stopping through fit_params
    # MultiOutputRegressor doesn't support eval_set natively,
    # so we train with fixed n_estimators (no early stopping at wrapper level)
    # Instead, do a quick single-output fit first to estimate best_iteration
    print("  [预估最优迭代次数] 用第1步 (t+15min) 做早停参考 ...")
    probe = XGBRegressor(
        n_estimators=800, learning_rate=0.05, max_depth=6,
        min_child_weight=5, subsample=0.8, colsample_bytree=0.7,
        reg_alpha=0.1, reg_lambda=1.0, objective='reg:squarederror',
        tree_method='hist', random_state=42, n_jobs=-1,
        eval_metric='rmse', early_stopping_rounds=30,
    )
    probe.fit(X_tr, y_train[:, 0],
              eval_set=[(X_vl, y_val[:, 0])], verbose=100)
    best_n = probe.best_iteration + 1
    print(f"  早停最优迭代: {best_n}")

    # Retrain all 16 outputs with best_n estimators
    final_base = XGBRegressor(
        n_estimators=best_n,
        learning_rate=0.05,
        max_depth=6,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.7,
        reg_alpha=0.1,
        reg_lambda=1.0,
        objective='reg:squarederror',
        tree_method='hist',
        random_state=42,
        n_jobs=-1,
    )
    model = MultiOutputRegressor(final_base, n_jobs=-1)
    model.fit(X_tr, y_train)
    print("  训练完成!")

    # Save model
    import joblib
    os.makedirs("solar_checkpoints", exist_ok=True)
    joblib.dump({"model": model, "norm_params": norm_params},
                "solar_checkpoints/best_model_xgboost.pkl")
    print("  模型已保存 → solar_checkpoints/best_model_xgboost.pkl")
    return model, norm_params


# ─────────────────────────────────────────────────────────────
# 4.  Evaluate
# ─────────────────────────────────────────────────────────────

def evaluate(data_dir='.'):
    print("\n[3/3] 模型评估")
    import joblib

    X_enc_test = np.load(os.path.join(data_dir, "X_enc_test.npy"))
    X_dec_test = np.load(os.path.join(data_dir, "X_dec_test.npy"))
    y_test     = np.load(os.path.join(data_dir, "y_test.npy"))

    saved = joblib.load("solar_checkpoints/best_model_xgboost.pkl")
    model      = saved["model"]
    norm_params = saved["norm_params"]
    cap        = norm_params["power"]["cap"]

    print(f"测试集: enc={X_enc_test.shape}, dec={X_dec_test.shape}, y={y_test.shape}")
    print(f"标称容量: {cap} MW")

    X_te = make_features(X_enc_test, X_dec_test)
    y_pred = np.array(model.predict(X_te), dtype=np.float32)
    y_pred = np.clip(y_pred, 0, None)     # power ≥ 0

    # ── Overall metrics ──
    print_metrics(y_test, y_pred, cap, label='XGBoost 测试集评估结果')

    # ── Per-step breakdown (all 16 points) ──
    step_metrics = print_per_step(y_test, y_pred, cap, num_steps=16)

    # ── Plot per-step ACC2 and RMSE ──
    steps     = list(range(1, 17))
    minutes   = [s * 15 for s in steps]
    step_acc2 = [m[1] for m in step_metrics]
    step_rmse = [m[2] for m in step_metrics]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    fig.suptitle('XGBoost – Per-step Accuracy (Test Set)', fontsize=13)

    axes[0].plot(minutes, step_acc2, 'o-', color='steelblue', linewidth=2)
    axes[0].set_xlabel('Forecast horizon (min)')
    axes[0].set_ylabel('ACC2')
    axes[0].set_title('ACC2 per prediction step')
    axes[0].set_xticks(minutes)
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(minutes, step_rmse, 's-', color='tomato', linewidth=2)
    axes[1].set_xlabel('Forecast horizon (min)')
    axes[1].set_ylabel('RMSE (MW)')
    axes[1].set_title('RMSE per prediction step')
    axes[1].set_xticks(minutes)
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    save_path = os.path.join(data_dir, 'xgboost_per_step_accuracy.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\nPer-step 图已保存 → {save_path}")
    plt.close()

    # ── Save predictions ──
    np.save(os.path.join(data_dir, "xgboost_y_pred_test.npy"), y_pred)
    np.save(os.path.join(data_dir, "xgboost_y_true_test.npy"), y_test)
    print("预测结果已保存 → xgboost_y_pred_test.npy / xgboost_y_true_test.npy")


# ─────────────────────────────────────────────────────────────
# 5.  Main
# ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="XGBoost 16-step solar power prediction (ED-comparable)")
    parser.add_argument("--skip-preprocess", action="store_true",
                        help="Skip solar_preprocess.py (use existing .npy files)")
    parser.add_argument("--csv-path", type=str,
                        default="/home/user/newPower/solar_station_1.csv")
    parser.add_argument("--data-dir", type=str, default="/home/user/newPower")
    parser.add_argument("--mode", type=str, default="all",
                        choices=["all", "train", "evaluate"])
    args = parser.parse_args()

    print("=" * 60)
    print("  XGBoost 太阳能功率预测 (16步, 可与 ED 对比)")
    print("=" * 60)

    # Step 1: preprocess (generate fixed splits)
    if not args.skip_preprocess and args.mode in ["all"]:
        print("\n[1/3] 数据预处理 (生成固定数据集划分)")
        from solar_preprocess import main as preprocess_main
        preprocess_main(csv_path=args.csv_path)
    else:
        print("\n[1/3] 跳过预处理, 使用已有 .npy 文件")

    # Step 2: train
    if args.mode in ["all", "train"]:
        train(data_dir=args.data_dir)

    # Step 3: evaluate
    if args.mode in ["all", "evaluate"]:
        evaluate(data_dir=args.data_dir)

    print("\n完成!")


if __name__ == "__main__":
    main()
